## Assignment Day 3 | 11th November 2020

**Questions 1:**
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [2]:
arr= np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

**Questions 2:**
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
numberList = []
numberList1 = []
m = 5
n = 5
print("\n")
for i in range(0, m):
    print("Enter number at location", i, ":")
    item = int(input())
    numberList.append(item)
    arr1 = np.array(numberList)
print("List1 ", numberList)
print("array 1 ", arr1)

print("\n")
for i in range(0, n):
    print("Enter number at location", i, ":")
    item = int(input())
    numberList1.append(item)
    arr2 = np.array(numberList1)
print("List2 ", numberList1)
print("array 2 ", arr2)

print("\n")
arr = np.concatenate((arr1, arr2))
print("Final array ", arr)





Enter number at location 0 :
6
Enter number at location 1 :
7
Enter number at location 2 :
8
Enter number at location 3 :
9
Enter number at location 4 :
10
List1  [6, 7, 8, 9, 10]
array 1  [ 6  7  8  9 10]


Enter number at location 0 :
11
Enter number at location 1 :
12
Enter number at location 2 :
13
Enter number at location 3 :
14
Enter number at location 4 :
15
List2  [11, 12, 13, 14, 15]
array 2  [11 12 13 14 15]


Final array  [ 6  7  8  9 10 11 12 13 14 15]


**Questions 3:**
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

In [5]:
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [6]:
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [7]:
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [8]:
print("Size of array: ", arr.size)

Size of array:  6


**Questions 4:**
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) #1D array

newarr = arr.reshape(4, 3) #2D array

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
# 1D array
arr = np.arange(4)
arr.shape

(4,)

In [11]:
#2D array
# make it as row vector by inserting an axis along first dimension
row_vec = arr[np.newaxis, :]
row_vec.shape 

(1, 4)

In [12]:
#1D array
exdim = np.array([1, 2]) 
print(exdim.shape) 

#2D array
exdim = np.expand_dims(exdim, axis = 0) 
print(exdim.shape) 

(2,)
(1, 2)


**Questions 5:**
Consider two square numpy arrays. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [13]:
starr= np.array( [1,2,3,4,5,6,7,8,9] ).reshape(3,3) #Square numpy array
starr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
starr1=np.array( [10,11,12,13,14,15,16,17,18] ).reshape(3,3) #Square numpy array
starr1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [15]:
# vertical stacking 
print("Vertical stacking:\n", np.vstack((starr,starr1))) 

Vertical stacking:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [16]:
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((starr,starr1))) 


Horizontal stacking:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


**Questions 6:**
How to get unique items and counts of unique items?

In [17]:
list1 = [10, 20, 10, 30, 40, 40] 
x = np.array(list1) 
print(np.unique(x)) 

[10 20 30 40]


In [18]:
print(len(np.unique(x)))

4
